const fs = require("fs"); 
require("dotenv").config();

module.exports = {
    prefix: process.env.PREFIX || ".",
    ownerName: process.env.OWNER_NAME || "Toxxic-Boy",
    ownerNumber: process.env.OWNER_NUMBER || "2348165846414",
    mode: process.env.MODE || "public",
    region: process.env.REGION || "Nigeria",
    botName: process.env.BOT_NAME || "Rias Gremory V3",
    exifPack: process.env.EXIF_PACK || "RIAS V3 LOVES",
    exifAuthor: process.env.EXIF_AUTHOR || "Toxxic",
    timeZone: process.env.TIME_ZONE || "Africa/Lagos",
    presenceStatus: process.env.PRESENCE_STATUS || "unavailable",
    autoRead: process.env.AUTO_READ === "true",
    autoViewStatus: process.env.AUTO_VIEW_STATUS === "true",
    autoReact: process.env.AUTO_REACT === "true",
    sessionId: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTUxnL1RtYy9FRlRxaWszS0c2YUVDZ29EZVVRZ1JQalFGdTlDNXRMalEwYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiK01vR1VOUlBvc1puUG4wMEtrdVZyWmNzT1E4dkhKVzRFYTV2bmVWRTFrOD0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJHSDBsbkRkSWFIL1ZNR1J0QXBVcUE1NDdzNDZsRkdtWGVrQ3dDNm5sQkZBPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJRdnlTRzBwclZ1eVU1UHkwdzkvNzhZeVV2bWQyOS9YUTJhdjcwUWpZSHdzPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjhBR01WLzRERVEyd3J3bncybVlZcTNEZStNV1dpYjdheVRnaEhGWDZzVTg9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImZ3ZXV3WWRrTXRSb2VDSWJ5clJRcG5Kc1BzblNPb3c2OWFaWXIyR08yZ2M9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWUlyMS81dk1GNmh2Vm5CLzBPQXQwTi9DNjBkQ1RnbUNUWWxkZlBqeVJVMD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOHdibHJoTWRiUGVXS3ZBWUVOMDhWYXhQNFduQVBZcmRscWtHdHFLdXAzYz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkxLL0xlWk8yLy8vck80dXIxWWN3cWhmVnZ3a1Q4NzJjM1BxalIyeTlBTGRONTZGZG00d1BjbWpUTVVXOUFPc1lTdFBWQUpCbnBKSVdXNFNhRE5kSkRnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NDAsImFkdlNlY3JldEtleSI6Im5TZFg2ejg5QWd4elhwakpHY1ZRSXBwV2N0NzN5WjFra2c3anUvcTFKN3M9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJyZWdpc3RlcmVkIjp0cnVlLCJwYWlyaW5nQ29kZSI6IlhQOTQ0QTRQIiwibWUiOnsiaWQiOiIyMzQ4MTQ2NjU0NTM5OjJAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoi8J2Vi/CdlaDwnZWhIPCdlLnwnZWg8J2VqvCTh7wg8JOGoSIsImxpZCI6IjYyNDE0ODMzOTAxNzA4OjJAbGlkIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNQMmExYzRPRUorRjdyMEdHQUVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJyYlVOK2piZVFLN1IvRHI4S2hxVWh6SFROZW1TTnhCMldLcEhNWUVveHlvPSIsImFjY291bnRTaWduYXR1cmUiOiJJajFaall2RCtUUVVPR0NQRXlJSDNQM0Q3VVA0VHNmcWN0RHAwSlpnNDQ3NnduYXFoL1E4NnREMWlMMTRXaDBZR0xLc1VYd2MrRGJzUmxyU1NDSHlBQT09IiwiZGV2aWNlU2lnbmF0dXJlIjoibklMbEdDMFJxaFI2K2UwVHRqTUZhTTdoRGJ5RUR0WTdnM1RIbm85Sngvdnc2MzltREpORmNmYktMN25raVlhWHpseVVRNUhiYkJSODBIOFJYYldWQ1E9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyMzQ4MTQ2NjU0NTM5OjJAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCYTIxRGZvMjNrQ3UwZnc2L0NvYWxJY3gwelhwa2pjUWRsaXFSekdCS01jcSJ9fV0sInBsYXRmb3JtIjoic21iaSIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0FnSURRPT0ifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzQwMzQxOTMzLCJsYXN0UHJvcEhhc2giOiIyUDFZaGYifQ==1",
    autoRejectEnabled: process.env.AUTO_REJECT_ENABLED || "false",
};

let file = require.resolve(__filename); 
fs.watchFile(file, () => {
    fs.unwatchFile(file); 
    console.log(`Update '${__filename}'`); 
    delete require.cache[file];
    require(file); 
});
